### ISSUE TITLE
Problem with convergence

### ISSUE THREAD

**Issue by michaelzevin** [COSMIC-PopSynth/COSMIC#120]
I ran into a problem that I think is regarding the convergence calculations. The failed run is located at 
`/projects/b1011/mzevin/cosmic/r_process/v10_lam0.5`

Below is from the submission log file: 

/home/mjz672/.conda/envs/cosmic-py36/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/mjz672/.conda/envs/cosmic-py36/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/mjz672/.local/lib/python3.6/site-packages/astropy/stats/histogram.py:209: RuntimeWarning: divide by zero encountered in double_scalars
  Nbins = max(1, np.ceil((dmax - dmin) / dx))
Traceback (most recent call last):
  File "/home/mjz672/.local/lib/python3.6/site-packages/astropy/stats/histogram.py", line 211, in freedman_bin_width
    bins = dmin + dx * np.arange(Nbins + 1)
ValueError: Maximum allowed size exceeded
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/mjz672/.conda/envs/cosmic-py36/bin/runFixedPop", line 293, in <module>
    kstar1_range, kstar2_range, log_file)
  File "/home/mjz672/.conda/envs/cosmic-py36/lib/python3.6/site-packages/cosmic/Match.py", line 163, in perform_convergence
    param_transform(bcm_conv_2[conv_param]).tolist()])
  File "/home/mjz672/.conda/envs/cosmic-py36/lib/python3.6/site-packages/cosmic/Match.py", line 55, in match
    mainHisto, binEdges = astroStats.histogram(np.array(dataCm[0]), bins='knuth')
  File "/home/mjz672/.local/lib/python3.6/site-packages/astropy/stats/histogram.py", line 79, in histogram
    da, bins = knuth_bin_width(a, True)
  File "/home/mjz672/.local/lib/python3.6/site-packages/astropy/stats/histogram.py", line 278, in knuth_bin_width
    dx0, bins0 = freedman_bin_width(data, True)
  File "/home/mjz672/.local/lib/python3.6/site-packages/astropy/stats/histogram.py", line 218, in freedman_bin_width
    'bins="scott"'.format(Nbins + 1))
ValueError: The inter-quartile range of the data is too small: failed to construct histogram with inf bins. Please use another bin method, such as bins="scott"
Closing remaining open files:dat_DeltaBurst_13_13.h5...done
----------------------------------------
PBS job ended

**Comment by katiebreivik** [comment]
@michaelzevin I'm looking into this today

**Comment by michaelzevin** [comment]
@katiebreivik just so you know, this happened for both of the runs I did with the natal kick maxwellian set to 10 km/s. Maybe this was the cause somehow?

**Comment by katiebreivik** [comment]
@michaelzevin how are you setting the natal kick? When I look at the Params.ini file it shows that natal_kick is zeros for the whole list?

**Comment by katiebreivik** [comment]
See this: https://github.com/COSMIC-PopSynth/COSMIC/pull/125 for a fix!
